services:
  master:
    container_name: master
    image: ghcr.io/teak-rosewood/bigdatadocker:nightly
    # If you are making changes to the docker file:
    # build: .
    ports:
      - 8088:8088
      - 9000:9000
      - 9870:9870
      - 4040:4040
    volumes:
      - ./workdir:/workdir
